version: "3.8"

services:
  coupon:
    image: greenpeace_mercadopago_coupon:dev
    container_name: greenpeace_mercadopago_coupon
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/app/coupon/
      - /home/app/coupon/node_modules/
    expose:
      - '3003'
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
    command: npm run client:start:development
    stdin_open: true
