FROM node:16

# RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY package*.json ./

RUN npm install -g nodemon
RUN npm install -g typescript
RUN npm install
RUN npm run types

# Copy source code to /app/src folder
# COPY . .
ENV NODE_ENV=development
CMD [ "npm", "run" ,  "server:start:watch" ]

EXPOSE 5000
