version: "3.8"
services:
  coupon:
    image: greenpeace_mercadopago_coupon:production
    container_name: greenpeace_mercadopago_coupon_production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/home/app/coupon/
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
