version: '3'
services:
  api:
    container_name: greenpeace__skunk_api_api
    image: greenpeace__skunk_api_api:dev
    build:
      context: ./
      dockerfile: Dockerfile-dev
    depends_on:
      - mongo
    ports:
      - "5050:80"
  mongo:
    container_name: greenpeace__skunk_api_mongo
    image: mongo:4
    restart: always
    volumes:
      - ./_shared_volume/db/:/data/db/
    ports:
      - "27016:27017"
