version: "3.7"

services:
  app:
    image: greenpeace_mercadopago_coupon:dev
    container_name: greenpeace_mercadopago_coupon
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/app/coupon/
      - /home/app/coupon/node_modules/
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    command: npm run client:start:development
    stdin_open: true
