version: "3.8"

services:
  api:
    image: greenpeace_greenlab_api:prod
    container_name: greenpeace_greenlab_api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/home/app/api/src
      - ./nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5001'
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
    # depends_on:
    #   - mongo
  # mongo:
  #   container_name: greenpeace_greenlab_mongo
  #   image: mongo:4
  #   restart: always
  #   volumes:
  #     - ./shared_volume/db/:/data/db/
  #   ports:
  #     - "27016:27017"
