version: "3.9"

services:
  api:
    image: greenpeace_greenlab_api:dev
    container_name: greenpeace_greenlab_api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/home/app/api/src
      - ./nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5003'
    ports:
      - '5003:5003'
    environment:
      - SERVER_PORT=5003
    command: npm run server:start:development
